### ISSUE TITLE
CI/CD 파이프라인 구축_Sen

### ISSUE THREAD

**Issue by Sena-Han** [2024-OpenSourceSoftware/J00#2]
## ⚡️Issue
2024 오픈소스소프트웨어 팀프로젝트 CI/CD 파이프라인 구축을 위한 DockerFile, JenkinsFile 등 추가 및 설정
## 🍀TO-DO
- [x] DockerFile 작성
- [x] JenkinsFile 작성
- [x] Webhook 설정 등 CI 환경 구축
- [x] Kubernetes Cluster 구축
- [x] Kubernetes Manifest File 작성
