### ISSUE TITLE
CI/CD 파이프라인 구축_Dain

### ISSUE THREAD

**Issue by kang-dain** [2024-OpenSourceSoftware/J00#3]
## ⚡Issue
J00 프로젝트의 CI/CD 파이프라인 구축을 위한 작업

## 🍀TO-DO
- [ ] Dockerfile 작성
- [ ] Jenkins 설정 및 Jenkinsfile 작성
- [ ] Kubernetes 클러스터 구축
- [ ] Kubernetes 매니페스트 작성
