### ISSUE TITLE
CI/CD 파이프라인 구축_ryxxng

### ISSUE THREAD

**Issue by LeeYeRyeong** [2024-OpenSourceSoftware/J00#5]
## ⚡️Issue

J00% 서비스의 CI/CD 구축
## 🍀TO-DO

- [x] Docker 파일 작성
- [ ] Jenkins 환경 셋팅 준비
- [ ] Jenkins 파일 작성
